name: Codespace Setup

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '.devcontainer/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify Expo setup
        run: |
          npx expo --version
          npx eas --version
      
      - name: Create Codespace configuration
        run: |
          echo "Codespace configuration verified"
          echo "Ready for development in GitHub Codespaces" 